name: Convert Draw.io to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet un déclenchement manuel

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Node.js pour utiliser drawio-batch
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Étape 3 : Installation de drawio-batch
      - name: Install drawio-batch
        run: |
          npm install -g @rlespinasse/drawio-batch

      # Étape 4 : Conversion du fichier .drawio en PDF
      - name: Convert Draw.io to PDF
        run: |
          mkdir -p output
          drawio-batch --export SOC.drawio --output output/diagramme.pdf --format pdf

      # Étape 5 : Upload du fichier PDF comme artefact
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Converted-PDF
          path: output/diagramme.pdf
